{"ast":null,"code":"import _regeneratorRuntime from \"/data/source/tuyendungvn-user-frontend-nextjs/node_modules/next/node_modules/@babel/runtime/regenerator\";\nimport _asyncToGenerator from \"/data/source/tuyendungvn-user-frontend-nextjs/node_modules/next/node_modules/@babel/runtime/helpers/esm/asyncToGenerator\";\nimport propertyApi from \"@common/config/graphql\";\nimport axios from \"axios\";\nimport { getToken } from \"./auth\";\n\nvar printErrorOfGraphQLFromServer = function printErrorOfGraphQLFromServer(error) {\n  var _error$networkError, _error$networkError$r, _error$networkError$r2;\n\n  var errorMessage = error === null || error === void 0 ? void 0 : (_error$networkError = error.networkError) === null || _error$networkError === void 0 ? void 0 : (_error$networkError$r = _error$networkError.result) === null || _error$networkError$r === void 0 ? void 0 : (_error$networkError$r2 = _error$networkError$r.errors[0]) === null || _error$networkError$r2 === void 0 ? void 0 : _error$networkError$r2.message;\n\n  if (!errorMessage) {\n    errorMessage = error === null || error === void 0 ? void 0 : error.message;\n  }\n\n  console.error(\"\\x1b[31m\", \"\\u26A0\\uFE0F [GraphQL Error] \".concat(errorMessage), \"\\x1b[37m\");\n};\n\nvar graphQLCommon = /*#__PURE__*/function () {\n  var _ref = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee(query, variables) {\n    var response, errors;\n    return _regeneratorRuntime.wrap(function _callee$(_context) {\n      while (1) {\n        switch (_context.prev = _context.next) {\n          case 0:\n            _context.prev = 0;\n            _context.next = 3;\n            return propertyApi.query({\n              query: query,\n              variables: variables,\n              context: {\n                headers: {\n                  Authorization: \"Bearer \".concat(getToken())\n                }\n              }\n            });\n\n          case 3:\n            response = _context.sent;\n            errors = (response === null || response === void 0 ? void 0 : response.errors) || [];\n            if (errors.length > 0) printErrorOfGraphQLFromServer(errors[0]);\n            return _context.abrupt(\"return\", response);\n\n          case 9:\n            _context.prev = 9;\n            _context.t0 = _context[\"catch\"](0);\n            printErrorOfGraphQLFromServer(_context.t0);\n            return _context.abrupt(\"return\", _context.t0);\n\n          case 13:\n          case \"end\":\n            return _context.stop();\n        }\n      }\n    }, _callee, null, [[0, 9]]);\n  }));\n\n  return function graphQLCommon(_x, _x2) {\n    return _ref.apply(this, arguments);\n  };\n}();\n\nvar axiosJSON = function axiosJSON(options) {\n  return axios(options).then(function (res) {\n    return res;\n  })[\"catch\"](function (error) {\n    return error;\n  });\n};\n\nexport { graphQLCommon, axiosJSON };","map":null,"metadata":{},"sourceType":"module"}